---
- name: Instalar Tomcat10
  hosts: ubuntu
  remote_user: ansible
  become: true
  tasks:
    - name: Instalar paquetes
      apt:
        upgrade: yes
        update_cache: yes
 
    - name: Crear usuario Tomcat
      user:
        name: tomcat
 
    - name: Crear grupo Tomcat
      group:
        name: tomcat
 
    - name: Instalar Java
      apt:
        name: openjdk-11-jdk
        state: present
 
    - name: Crear directorio Tomcat
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: Descargar y descomprimir tomcat10 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Cambiar propietario del directorio /opt/tomcat10
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
 
    - name: Copiar servicio Tomcat a systemd
      copy:
        src: /opt/servicios/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
 
    - name: Iniciar y habilitar Tomcat 10
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
