- name: Upgrade paquetes en Ubuntu
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Actualizar paquetes en Rocky
  dnf:
    name: "*"
    state: latest
  when: ansible_facts['distribution'] == "Rocky"