- name: Añadir .my.cnf
  template:
    src: ../files/my.cnf
    dest: /home/ansible/.my.cnf

- name: Crear base de datos todo
  community.mysql.mysql_db:
    name: todo
    state: present

- name: Crear tablas en base de datos todo
  community.mysql.mysql_query:
    login_db: todo
    query: 
    - CREATE TABLE `users` (`id` int(3) NOT NULL AUTO_INCREMENT,`first_name` varchar(20) DEFAULT NULL,`last_name` varchar(20) DEFAULT NULL,`username` varchar(250) DEFAULT NULL,`password` varchar(20) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB
    - CREATE TABLE `todos` (`id` bigint(20) NOT NULL AUTO_INCREMENT,`description` varchar(255) DEFAULT NULL,`is_done` bit(1) NOT NULL,`target_date` datetime(6) DEFAULT NULL,`username` varchar(255) DEFAULT NULL,`title` varchar(255) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=8

- name: Crear usuario con permisos en base de datos todo
  community.mysql.mysql_user:
    name: todo
    password: prueba2022
    priv: 'todo.*:ALL,GRANT'
    state: present

- name: Borrar .my.cnf
  file:
    path: /home/ansible/.my.cnf
    state: absent