- name: Añadir .my.cnf
  template:
    src: ../files/my.cnf
    dest: /home/ansible/.my.cnf
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Crear base de datos para proyecto
  command: |
    mysql -p{{ mariadb_root_password }} -ne "{{ item }}"
  with_items:
    - CREATE DATABASE todo
    - USE todo
    - CREATE TABLE `users` (
      `id` int(3) NOT NULL AUTO_INCREMENT,
      `first_name` varchar(20) DEFAULT NULL,
      `last_name` varchar(20) DEFAULT NULL,
      `username` varchar(250) DEFAULT NULL,
      `password` varchar(20) DEFAULT NULL,
      PRIMARY KEY (`id`)
      ) ENGINE=InnoDB;
    - CREATE TABLE `todos` (
      `id` bigint(20) NOT NULL AUTO_INCREMENT,
      `description` varchar(255) DEFAULT NULL,
      `is_done` bit(1) NOT NULL,
      `target_date` datetime(6) DEFAULT NULL,
      `username` varchar(255) DEFAULT NULL,
      `title` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
      ) ENGINE=InnoDB AUTO_INCREMENT=8;
  changed_when: False

- name: Borrar .my.conf
  file:
    path: /home/ansible/.my.cnf
    state: absent
  when: ansible_facts['distribution'] == "Ubuntu"