- name: Crear usuario Tomcat
  user:
    name: tomcat

- name: Crear grupo Tomcat
  group:
    name: tomcat

- name: Crear directorio JDK 1.8
  file:
    path: /opt/jdk1.8
    recurse: yes

- name: Descargar y descomprimir java 1.8 
  unarchive:
    src: https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u332-b09/openlogic-openjdk-8u332-b09-linux-x64.tar.gz
    dest: /opt/jdk1.8
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Crear directorio Tomcat
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes

- name: Descargar y descomprimir tomcat9 
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
    dest: /opt/tomcat9
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Cambiar propietario del directorio /opt/tomcat9
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copiar servicio Tomcat a systemd
  copy:
    src: ../files/tomcat.service
    dest: /etc/systemd/system/
    mode: 0755

- name: Iniciar y habilitar Tomcat 9
  systemd:
    name: tomcat
    state: started
    daemon_reload: true